### ISSUE TITLE
Make sure that GDAL_DATA is set and still present in the package

### ISSUE THREAD

**Issue by yeesian** [visr/GDAL.jl#30]
```
ERROR: LoadError: LoadError: GDALError (Failure, code 4):
    Unable to open EPSG support file gcs.csv.
Try setting the GDAL_DATA environment variable to point to the
directory containing EPSG csv files.
```

Got it from https://travis-ci.org/yeesian/ArchGDAL.jl/jobs/146128237

seems related to https://github.com/conda/conda-recipes/pull/267

**Comment by yeesian** [comment]
Maybe we can try setting it ourselves: http://stackoverflow.com/a/25693547.

**Comment by visr** [comment]
> Maybe we can try setting it ourselves

That seems to be a good solution. If it is not set as an environment variable, we could set it using `CPLSetConfigOption` (see also #36). I tried (after removing my GDAL_DATA environment variable) this and it worked:

```julia
using GDAL
ccall((:CPLSetConfigOption,:gdal201),Void,(Cstring,Cstring),
    "GDAL_DATA","c:\\OSGeo4W64\\share\\gdal")
srs = GDAL.newspatialreference(C_NULL)
GDAL.importfromepsg(srs, 4326)
```

Whereas it would crash without the `CPLSetConfigOption`

But the question is, how do we find the right path?

**Comment by yeesian** [comment]
> But the question is, how do we find the right path?

It seems that we just need to run:
`$ gdal-config --datadir`

at the commandline. Source file here: https://github.com/OSGeo/gdal/blob/fd001db37bcf7a3f791de3bf5bbf6247586e4680/gdal/apps/gdal-config.in

HT: https://github.com/ContinuumIO/anaconda-issues/issues/831

**Comment by visr** [comment]
That seems to be the solution indeed, however not for Windows, where `gdal-config` is not available.
[Rasterio](https://github.com/mapbox/rasterio/tree/994def271a14126e690a080ead816626a70fdeb0#windows-1) seems to require the user to set it manually on Windows.

**Comment by yeesian** [comment]
Might the instructions in https://github.com/ContinuumIO/anaconda-issues/issues/221#issuecomment-283557649 help?

**Comment by visr** [comment]
That assumes the GDAL_DATA folder is at a specific relative path from the shared library, which is a heuristic we could use but not guaranteed to be correct. Taking 3 common GDAL installation methods on Windows, this is where it is put:

- OSGeo4W: `../share/gdal`
- Conda (conda-forge gdal): `../share/gdal`
- openSUSE Build Service (used when nothing suitable is found on the system): `../share`

So we could try these relative paths and otherwise prompt the user to set `GDAL_DATA`. We can always fix it first for Unix and later for Windows of course.

**Comment by yeesian** [comment]
Yeah, I don't know of any other way for now.
