### ISSUE TITLE
Wrap pointers into julian types

### ISSUE THREAD

**Issue by yeesian** [visr/GDAL.jl#7]
We should define e.g.

```julia
immutable GDALDriver
    ptr::GDALDriverH
end
```

for each of the typealiases in https://github.com/visr/GDAL.jl/blob/22b70b7b74ac75d645c5361e779a38474df860a3/gen/rewriter.jl#L29-L54

And the methods in `src/gdal_*` and `src/ogr_*` should be defined on these types, rather than on `Ptr{Void}`.

Should this be done in the rewriter?

**Comment by visr** [comment]
I'm working on this (and a few other things) in the `regenerate` branch. Relevant to this issue is commit 264d7a87aa5cd5e588bee241d780056f1dc68099.

The new examples from Jiahao in http://docs.julialang.org/en/latest/manual/calling-c-and-fortran-code/#some-examples-of-c-wrappers helped a lot.

Feedback welcome :)

**Comment by meggart** [comment]
This very cool and thanks for pointing to the example in the manual. I guess your goal is to mimic the type hierachy defined by GDAL (http://www.gdal.org/classGDALMajorObject.html)? I see through function signatures like this `function getmetadata{T <: GDALMajorObjectH}(arg1::Ptr{T},arg2)` this should integrate with the julia type system in a very smooth way. :+1:

**Comment by visr** [comment]
Yes that's right. After making the change from `typealias`ing everything to `Ptr{Void}` the test for `getmetadata` actually started failing. This was because I called it with a `Ptr{GDALDriverH}` (as done [here](http://www.gdal.org/gdal_tutorial.html)), but the julia function only accepted `Ptr{GDALMajorObjectH}`.

By defining `abstract GDALDriverH <: GDALMajorObjectH` in
https://github.com/visr/GDAL.jl/blob/264d7a87aa5cd5e588bee241d780056f1dc68099/src/types.jl
And then using type parameters in the function signature, we can make this work.

**Comment by yeesian** [comment]
nice work! I'm curious: is the plan to make the "leaf" types concrete, or abstract? e.g.
```julia
abstract GDALMajorObjectH
abstract GDALDatasetH <: GDALMajorObjectH

immutable OGRDataSource <: GDALDatasetH
   ptr::Ptr{Void}
end
```
instead of
```julia
abstract GDALMajorObjectH
abstract GDALDatasetH <: GDALMajorObjectH
abstract OGRDataSourceH <: GDALDatasetH

immutable OGRDataSource <: OGRDataSourceH
   ptr::Ptr{Void}
end
```

I lean towards the former, but can be convinced either way. I ask because https://github.com/visr/GDAL.jl/commit/264d7a87aa5cd5e588bee241d780056f1dc68099 suggests it should be the latter, so I'm wondering if there are convincing arguments for it?

**Comment by visr** [comment]
What I have right now is your last example. So indeed I don't see the benefit of having concrete types. Are there any advantages to using one of your first two examples compared to this?

As a way to hide all the ugly `Ptr{}` business, can't we just define `OGRDataSource = Ptr{OGRDataSourceH}` and use that everywhere?

**Comment by yeesian** [comment]
Yup, indeed I don't know of any advantages to the first two examples I listed, and it's only from your `regenerate` branch that I learnt about the last example. Just one more question: does it make more sense to do
```julia
abstract GDALMajorObjectH
abstract GDALDatasetH <: GDALMajorObjectH
abstract OGRDataSourceH <: GDALDatasetH

typealias OGRDataSource Ptr{OGRDataSourceH}
```
or
```julia
abstract GDALMajorObject
abstract GDALDataset <: GDALMajorObject
abstract OGRDataSource <: GDALDataset

typealias OGRDataSourceH Ptr{OGRDataSource}
```
?

(Observe where the `H` goes)

**Comment by meggart** [comment]
I would prefer your first example. This would mean that we don't have the `H` in user-facing code. For example in `RasterIO.jl` we can define the `Raster` type as:

````julia
type Raster{T,N}
    dataset::GDALDataset
    width::Int32
    height::Int32
    nband::Int32
end
````

IMO this reads better than having to carry around the `H` all the way.

**Comment by visr** [comment]
Thanks for the feedback, very valuable.

Looking at http://www.gdal.org/gdal_8h.html it says:

`typedef void * GDALMajorObjectH`: Opaque type used for the C bindings of the C++ GDALMajorObject class.
`typedef void * GDALDatasetH`: Opaque type used for the C bindings of the C++ GDALDataset class.

We are wrapping the C API, which ends with H. Unlike the C API we no longer `typedef void *`/`typealias Ptr{Void}` the types, we basically borrow the hierarchy from the C++ API. However even though they are typed now, they will remain opaque pointers. So there is never really a need to use the abstract types, only their pointers. I would prefer using `typealias GDALDataset Ptr{GDALDatasetH}` because `GDALDataset` is shorter/easier to remember.

We could also then define `GDALDataset() = convert(GDALDataset, C_NULL)`, something we need pretty often.

You are right that it'll be only a thin wrapper, but I would like to make it usable by itself as well. I feel that not defining the typealiases would make it unnecessarily complex to use.

**Comment by yeesian** [comment]
> "I would prefer using `typealias GDALDataset Ptr{GDALDatasetH}` because `GDALDataset` is shorter/easier to remember."

It's clear which way the vote swings then (:

In that case, it'll be nice to have a way to remind developers to handle the pointers appropriately (terminating/closing them, etc), since `GDALDataset` might look deceptively like a Julia object, whereas the [`H`]andle in `GDALDatasetH` would be an easy signifier. The whole point is to make pointers "unfriendly"/not-user-facing, and hiding that behind a nicer-sounding name does not address the responsibility that comes with it.

**Comment by visr** [comment]
Hmm after digesting your and Fabian's comments and working through the API tutorial a bit more I am starting to think it is better to keep it as is, with the abstract GDALDatasetH as it is created by Clang.jl, and plain Ptr{GDALDatasetH} without typealias. The typealias can't be used in function signatures anyway if you want to allow subtypes as well, since you need a parametric Ptr{T}.

**Comment by yeesian** [comment]
> Hmm after digesting your and Fabian's comments and working through the API tutorial a bit more I am starting to think it is better to keep it as is, with the abstract GDALDatasetH as it is created by Clang.jl, and plain Ptr{GDALDatasetH} without typealias. The typealias can't be used in function signatures anyway if you want to allow subtypes as well, since you need a parametric Ptr{T}.

Ah, yeah that's a good point and I'm in full agreement.
